name: Publish kermite_rp_unified

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/kermite_rp_unified.yaml"
      - "kermite_rp_unified/**"

defaults:
  run:
    working-directory: kermite_rp_unified

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Install Platform
        run: pio pkg update --global --platform "https://github.com/maxgerhardt/platform-raspberrypi.git"

      - name: Build PlatformIO Project
        run: pio run

      - name: Upload to Firmix
        continue-on-error: true
        run: |
          curl -X POST -H "Authorization: token ${{secrets.FIRMIX_TOKEN}}" \
            -F readme=@./readme.md -F metadata=@./project.fm1.json \
            -F firmware=@./.pio/build/generic/firmware.uf2 \
            https://firmix.deno.dev/api/project/upload
